export const API_KEY: string = 'jNhxKrI5jpcAALtvFCVwzjtPB6BVW0mh';
export const USERS_API: string = 'http://localhost:8000/';
export const TOP_STORIES =
  'https://api.nytimes.com/svc/topstories/v2/home.json?api-key=' + API_KEY;
export const WORLD_STORIES =
  'https://api.nytimes.com/svc/topstories/v2/world.json?api-key=' + API_KEY;
export const SCIENCE_STORIES =
  'https://api.nytimes.com/svc/topstories/v2/science.json?api-key=' + API_KEY;
export const ARTICLES_SEARCH =
  'https://api.nytimes.com/svc/search/v2/articlesearch.json?api-key=' + API_KEY;
